CREATE SCHEMA [INTERNAL_ETL]
AUTHORIZATION [dbo];










GO

EXEC sys.sp_addextendedproperty
  @name = N'MS_Description'
  , @value = N'Schema is used for objects like tables, views, stored procedures, functions etc. generated by the ETL stored procedure framework based on objects and metadata in schema UTIL_ETL'
  , @level0type = N'SCHEMA'
  , @level0name = N'INTERNAL_ETL';
GO
