CREATE VIEW [INTERNAL_LOOKUP].[DIL_td_AccountsPayableLineItem] AS
--Zunächst werden die Delta-Datensätze pro BUKRS, GJAHR, BELNR und BUZEI anhand des Requests durchnummeriert
WITH ap4_numbered AS (
  SELECT
    *
    , ROW_NUMBER() OVER (PARTITION BY BUKRS, GJAHR, BELNR, BUZEI ORDER BY JobTST DESC, TS_SEQUENCE_NUMBER DESC) AS r
  FROM [DAL_SAP].[td_0FI_AP_4]
)

--Es wird pro BUKRS, GJAHR, BELNR und BUZEI nur der zuletzt gültige Datensatz ausgegeben
--Stornierte Belege werden nicht berücksichtigt (z.B. alle UPDMODs ungleich Leerstring)
, ap4 AS (
  SELECT *
  FROM ap4_numbered
  WHERE r = 1 AND UPDMOD = ''
)

SELECT
  [getDayTimeIDFromDate_day].returnValue AS [day_Time_ID_PostingDate]
  , [BELNR] AS [AccountingDocumentNumber_KEY]
  , [BUZEI] AS [AccountingDocumentPostingNumber_KEY]
  , [KOART] AS [AccountType_KEY]
  , [XARCH] AS [ArchiveIndicator_KEY]
  , [ZUONR] AS [AssignmentNumber_KEY]
  , [ZFBDT] AS [BaselineDateDueDate]
  , [FILKD] AS [BranchAccountNumber_KEY]
  , [KTOPL] AS [ChartOfAccounts_KEY]
  , [AUGDT] AS [ClearingDate]
  , [AUGBL] AS [ClearingDocumentNumber_KEY]
  , [BUKRS] AS [CompanyCode_KEY]
  , [LAND1] AS [Country_KEY]
  , [CPUDT] AS [CreationDate]
  , [KKBER] AS [CreditControlArea_KEY]
  , [SHKZG] AS [DebitCreditIndicator_KEY]
  , [BLDAT] AS [DocumentDate]
  , [BSTAT] AS [DocumentStatus_KEY]
  , [BLART] AS [DocumentType_KEY]
  , [SK1DT] AS [DueDateCashDiscount1]
  , [SK2DT] AS [DueDateCashDiscount2]
  , [NETDT] AS [DueDateNetPayment]
  , [MABER] AS [DunningArea_KEY]
  , [MANSP] AS [DunningBlock_KEY]
  , [MSCHL] AS [DunningKey_KEY]
  , [MANST] AS [DunninngLevel_KEY]
  , [MONAT] AS [FiscalPeriod]
  , [GJAHR] AS [FiscalYear]
  , [FISCPER] AS [FiscalYearPeriod]
  , [REBZJ] AS [FiscalYearRelevantInvoice]
  , [FISCVAR] AS [FiscalYearVariant_KEY]
  , [HKONT] AS [GLAccount_KEY]
  , [SAKNR] AS [GLAccountNumber_KEY]
  , [REBZG] AS [InvoiceDocumentNumber_KEY]
  , [REBZZ] AS [InvoiceDocumentPostingNumber_KEY]
  , [SGTXT] AS [ItemText_DESC]
  , [MADAT] AS [LastDunningDate]
  , [XNEGP] AS [NegativePostingFlag_KEY]
  , [ZBD3T] AS [NetPaymentTermsPeriod_QTY]
  , [ZLSPR] AS [PaymentBlock_KEY]
  , [ZLSCH] AS [PaymentMethod_KEY]
  , [BUDAT] AS [PostingDate]
  , [BSCHL] AS [PostingKey_KEY]
  , [RSTGR] AS [ReasonCodeForPayments_KEY]
  , [XBLNR] AS [ReferenceDocumentNumber_KEY]
  , [AWKEY] AS [ReferenceKey_KEY]
  , [XREF1] AS [ReferenceKeyBusinessPartner1_KEY]
  , [XREF2] AS [ReferenceKeyBusinessPartner2_KEY]
  , [XREF3] AS [ReferenceKeyDocumentItem_KEY]
  , [AWTYP] AS [ReferenceTransaction_KEY]
  , [VBELN] AS [SalesDocumentNumber_KEY]
  , [UMSKZ] AS [SpecialGLIndicator_KEY]
  , [STATUSPS] AS [StatusOfFIItem_KEY]
  , [UPOSZ] AS [SubitemNumber_KEY]
  , [ZTERM] AS [TermsOfPayment_KEY]
  , [UMSKS] AS [TransactionClassSpecialLedger_KEY]
  , [UPDMOD] AS [UpdateMode_KEY]
  , [LIFNR] AS [Vendor_KEY]
  , [PROJK] AS [WBSElement_PROJK_KEY]
  , [ZBD1P] AS [CashDiscount1_PCT]
  , [ZBD2P] AS [CashDiscount2_PCT]
  , [ZBD1T] AS [CashDiscountDays1_QTY]
  , [ZBD2T] AS [CashDiscountDays2_QTY]
  , [DMBTR] AS [LC_Amount_AMT]
  , [SKNTO] AS [LC_CashDiscount_AMT]
  , [DMHAB] AS [LC_Credit_AMT]
  , [LCURR] AS [LC_Currency_KEY]
  , [DMSOL] AS [LC_Debit_AMT]
  , [DMSHB] AS [LC_DebitCredit_AMT]
  , [DMBE2] AS [LC2_Amount_AMT]
  , [HWAE2] AS [LC2_Currency_KEY]
  , [DMBE3] AS [LC3_Amount_AMT]
  , [HWAE3] AS [LC3_Currency_KEY]
  , [WRBTR] AS [TC_Amount_AMT]
  , [WSKTO] AS [TC_CashDiscount_AMT]
  , [WRHAB] AS [TC_Credit_AMT]
  , [WAERS] AS [TC_Currency_KEY]
  , [WRSOL] AS [TC_Debit_AMT]
  , [WRSHB] AS [TC_DebitCredit_AMT]
  , [SKFBT] AS [TC_EligibleCashDiscount_AMT]
FROM ap4
CROSS APPLY UTIL.getDayTimeIDFromDate([BUDAT]) [getDayTimeIDFromDate_day]
